# Generated by Django 4.0.1 on 2022-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
