# Generated by Django 4.0.1 on 2022-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='static/accounts/default.jpg', upload_to='profiles/'),
        ),
    ]
